load("//tools/dev/go:defs.bzl", "go_largetest")

go_largetest(
    name = "testplan_test",
    size = "small",
    srcs = ["interface_test.go"],
    deps = [
        "//common/gopkg/testtool",
        "//projects/game/pkg/token",
        "//projects/game/runtime",
        "//projects/game/runtime/testplan/fakeagent",
        "@com_github_coder_websocket//:websocket",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials/insecure",
        "@org_golang_google_protobuf//encoding/protojson",
    ],
)
