name: deploy.iface
desc: "deploy service environment"
services:
  - infra:
      app: deploy
      resource: mongodb
      profile: dev-single
      name: mongo
  - artifact:
      path: //projects/infra/deploy/service.yaml
      name: service-iface
    http:
      hostnames:
        - infra.liukexin.com
      matches:
        - backend: http
          path:
            type: PathPrefix
            value: /v1/deploy
