version: "3.0"
name: wrapper
app: grpc-hello-world-ts
kind: stateless
desc: grpc-js testplan HTTP wrapper
ports:
  - name: http
    port: 80
artifacts:
  - name: wrapper
    target: //experimental/ts/grpc_hello_world/testplan:cmd_image
    tls: true
