load("@rules_go//go:def.bzl", "go_library")
load("//tools/release/wails:defs.bzl", "wails_app", "wails_asset_library", "wails_asset_provider")

wails_asset_library(
    name = "assets_lib",
    src = "//tools/release/wails/testdata/asset_library:dist",
    importpath = "dominion/tools/wails/testdata/app/assets",
    visibility = ["//visibility:public"],
)

wails_asset_provider(
    name = "assets",
    importpath = "dominion/tools/wails/testdata/app/assets",
    library = ":assets_lib",
    visibility = ["//visibility:public"],
)

go_library(
    name = "app_lib",
    srcs = ["main.go"],
    importpath = "dominion/tools/release/wails/testdata/app",
    visibility = ["//visibility:private"],
)

wails_app(
    name = "app",
    assets = ":assets",
    binary_name = "wails-app-fixture",
    go_library = ":app_lib",
    platform = "windows/amd64",
    visibility = ["//visibility:public"],
)
