load("//tools/dev/go:defs.bzl", "go_largetest")

go_largetest(
    name = "testplan_test",
    size = "small",
    srcs = [
        "helpers_test.go",
        "prompt_test.go",
    ],
    deps = [
        "//common/gopkg/testtool",
        "//projects/game",
        "//projects/game/pkg/gameconst",
        "@com_github_gorilla_websocket//:websocket",
        "@org_golang_google_protobuf//encoding/protojson",
    ],
)

go_largetest(
    name = "session_test",
    size = "small",
    srcs = [
        "helpers_test.go",
        "session_test.go",
    ],
    deps = [
        "//common/gopkg/testtool",
        "//projects/game",
        "@com_github_gorilla_websocket//:websocket",
        "@org_golang_google_protobuf//encoding/protojson",
    ],
)

go_largetest(
    name = "agent_lifecycle_test",
    size = "small",
    srcs = [
        "agent_lifecycle_test.go",
        "helpers_test.go",
    ],
    deps = [
        "//common/gopkg/testtool",
        "//projects/game",
        "//projects/game/pkg/gameconst",
        "@com_github_gorilla_websocket//:websocket",
        "@org_golang_google_protobuf//encoding/protojson",
    ],
)

go_largetest(
    name = "agent_checkpoint_test",
    size = "small",
    srcs = [
        "agent_checkpoint_test.go",
        "helpers_test.go",
    ],
    deps = [
        "//common/gopkg/testtool",
        "//projects/game",
        "//projects/game/pkg/gameconst",
        "@com_github_gorilla_websocket//:websocket",
        "@org_golang_google_protobuf//encoding/protojson",
    ],
)

go_largetest(
    name = "agent_dialog_test",
    size = "small",
    srcs = [
        "agent_dialog_test.go",
        "helpers_test.go",
    ],
    deps = [
        "//common/gopkg/testtool",
        "//projects/game",
        "//projects/game/pkg/gameconst",
        "@com_github_gorilla_websocket//:websocket",
        "@org_golang_google_protobuf//encoding/protojson",
    ],
)

go_largetest(
    name = "agent_multimodal_test",
    size = "small",
    srcs = [
        "agent_multimodal_test.go",
        "helpers_test.go",
    ],
    deps = [
        "//common/gopkg/testtool",
        "//projects/game",
        "//projects/game/pkg/gameconst",
        "@com_github_gorilla_websocket//:websocket",
        "@org_golang_google_protobuf//encoding/protojson",
    ],
)

go_largetest(
    name = "agent_operation_test",
    size = "small",
    srcs = [
        "agent_operation_test.go",
        "helpers_test.go",
    ],
    deps = [
        "//common/gopkg/testtool",
        "//projects/game",
        "//projects/game/pkg/gameconst",
        "@com_github_gorilla_websocket//:websocket",
        "@org_golang_google_protobuf//encoding/protojson",
    ],
)
