load("//tools/dev/go:defs.bzl", "go_largetest")
load("//tools/release:defs.bzl", "artifact_image", "artifact_pkg_go")

artifact_pkg_go(
    name = "service_pkg",
    app = "grpc-chain",
    binary = "//experimental/grpc_chain/testplan/gateway:gateway",
    service = "gateway",
)

artifact_image(
    name = "cmd_image",
    app = "grpc-chain",
    pkg = ":service_pkg",
    service = "gateway",
)

go_largetest(
    name = "testplan_test",
    size = "small",
    srcs = ["interface_test.go"],
    deps = ["//common/gopkg/testtool"],
)
