packages:
  - experimental/ts/*

catalog:
  "@sveltejs/vite-plugin-svelte": "^5.0.3"
  "@types/node": "^22.19.19"
  svelte: "^5.33.0"
  typescript: "^6.0.2"
  vite: "^6.4.2"
  vitest: "^3.2.4"
ignoredBuiltDependencies: []
onlyBuiltDependencies: []
