load("//tools/release:defs.bzl", "artifact_image", "artifact_pkg_go")

artifact_pkg_go(
    name = "service_pkg",
    app = "game",
    binary = "//projects/game/prompt/cmd:cmd",
    service = "prompt",
)

artifact_image(
    name = "cmd_image",
    app = "game",
    pkg = ":service_pkg",
    service = "prompt",
    visibility = ["//visibility:public"],
)
