# keep
load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_run_binary", "js_test")
load("@npm//:defs.bzl", "npm_link_all_packages")

npm_link_all_packages()

filegroup(
    name = "srcs",
    srcs = [
        "index.html",
        "package.json",
        "tsconfig.json",
        "vite.config.ts",
    ] + glob(["src/**"]),
)

genrule(
    name = "vite_build_entry",
    outs = ["vite_build_entry.mjs"],
    cmd = "printf '%s\\n' \"import './node_modules/vite/bin/vite.js';\" > $@",
)

js_binary(
    name = "vite_build",
    data = [
        ":node_modules",
    ],
    entry_point = ":vite_build_entry",
)

js_run_binary(
    name = "dist",
    srcs = [
        ":node_modules",
        ":srcs",
    ],
    args = ["build"],
    chdir = package_name(),
    out_dirs = ["dist"],
    tool = ":vite_build",
    visibility = [
        "//projects/game/windows_agent:__pkg__",
        "//projects/game/windows_agent/assets:__pkg__",
    ],
)

genrule(
    name = "vitest_entry",
    outs = ["vitest_entry.mjs"],
    cmd = "printf '%s\\n' \"import './node_modules/vitest/vitest.mjs';\" > $@",
)

js_test(
    name = "vitest_test",
    args = ["run"],
    data = [
        "vitest.config.ts",
        ":node_modules",
        ":srcs",
    ],
    entry_point = ":vitest_entry",
)
