load("@rules_go//go:def.bzl", "go_binary", "go_library")

exports_files(["defs.bzl"])

go_library(
    name = "release_lib",
    srcs = ["zip_package.go"],
    importpath = "dominion/projects/game/windows_agent/release",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "zip_package",
    embed = [":release_lib"],
    visibility = ["//visibility:private"],
)
