load("@rules_go//go:def.bzl", "go_library")
load("//tools/dev/go:defs.bzl", "go_unittest")

go_library(
    name = "const",
    srcs = ["const.go"],
    importpath = "dominion/projects/game/pkg/const",
    visibility = ["//visibility:public"],
)

go_unittest(
    name = "const_test",
    srcs = ["const_test.go"],
    embed = [":const"],
)
