load("//tools/release/wails:defs.bzl", "wails_asset_library", "wails_asset_provider")

wails_asset_library(
    name = "assets_lib",
    src = "//projects/game/desktop/frontend:dist",
    importpath = "dominion/projects/game/desktop/assets",
    visibility = ["//visibility:public"],
)

wails_asset_provider(
    name = "assets",
    importpath = "dominion/projects/game/desktop/assets",
    library = ":assets_lib",
    visibility = ["//visibility:public"],
)
