load("@rules_go//go:def.bzl", "go_library")
load("//tools/dev/go:defs.bzl", "go_unittest")

go_library(
    name = "bootstrap",
    srcs = [
        "bootstrap.go",
        "component.go",
        "grpc.go",
        "http.go",
        "option.go",
        "otel.go",
        "stage.go",
    ],
    importpath = "dominion/common/gopkg/bootstrap",
    visibility = ["//visibility:public"],
    deps = [
        "//common/gopkg/otel",
        "@org_golang_google_grpc//:grpc",
    ],
)

go_unittest(
    name = "bootstrap_test",
    srcs = [
        "bootstrap_test.go",
        "grpc_test.go",
        "http_test.go",
        "otel_test.go",
    ],
    embed = [":bootstrap"],
    deps = [
        "//common/gopkg/otel",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials/insecure",
    ],
)
