load("@rules_go//go:def.bzl", "go_library")
load("//tools/dev/go:defs.bzl", "go_unittest")

go_library(
    name = "stream",
    srcs = ["binder.go"],
    importpath = "dominion/projects/game/proxy/runtime/stream",
    visibility = ["//visibility:public"],
    deps = [
        "//projects/game",
        "@org_golang_x_sync//errgroup",
    ],
)

go_unittest(
    name = "stream_test",
    srcs = ["binder_test.go"],
    embed = [":stream"],
    deps = ["//projects/game"],
)
