load("//tools/release:defs.bzl", "artifact_image", "artifact_pkg_go")

artifact_pkg_go(
    name = "service_pkg",
    app = "dsh-demo",
    binary = "//experimental/dsh/demo/fake-llm/cmd:cmd",
    service = "fake-llm",
)

artifact_image(
    name = "cmd_image",
    app = "dsh-demo",
    pkg = ":service_pkg",
    service = "fake-llm",
    visibility = ["//visibility:public"],
)
