load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "gateway_lib",
    srcs = ["main.go"],
    importpath = "dominion/experimental/grpc_chain/testplan/gateway",
    visibility = ["//visibility:private"],
    deps = [
        "//common/gopkg/bootstrap",
        "//common/gopkg/grpc",
        "//common/gopkg/grpc/solver",
        "//common/gopkg/http",
        "//common/gopkg/otel",
        "//experimental/grpc_chain",
        "@grpc_ecosystem_grpc_gateway//runtime",
        "@org_golang_google_grpc//:grpc",
    ],
)

go_binary(
    name = "gateway",
    embed = [":gateway_lib"],
    visibility = ["//visibility:public"],
)
