load("@rules_go//go:def.bzl", "go_library")
load("//tools/dev/go:defs.bzl", "go_unittest")

go_library(
    name = "constants",
    srcs = ["constants.go"],
    importpath = "dominion/common/gopkg/constants",
    visibility = ["//visibility:public"],
)

go_unittest(
    name = "constants_test",
    srcs = ["constants_test.go"],
    embed = [":constants"],
)
