name: cmd
app: mongo-demo
desc: mongo demo gRPC service and HTTP gateway
artifacts:
  - name: cmd
    type: deployment
    target: :cmd_image
    tls: true
    ports:
      - name: grpc
        port: 50051
      - name: http
        port: 80
