/**
 * MemoryClient — gRPC client for the MemoryService (spec 039 US2).
 *
 * Resolves the memory service via the dominion resolver and calls the
 * Create/Update/Delete/ListMemories RPCs to read and mutate the session's
 * long-term memory entries (resource pattern
 * `templates/{template}/sessions/{session}/memories/{memory}` —
 * `specs/039-planner-memory-calibration/contracts/memory-mcp-contract.md` §3;
 * the MemoryService storage API is unchanged by spec 039 — it stays
 * memory_id-based, all hermes-style conversion happens in the agent's
 * `memory-mcp.ts`).
 *
 * This is a pass-through gRPC client ONLY (contract §3): it never performs
 * hermes-style old_text matching or memory_id generation — those live in
 * `mcp/memory/memory-mcp.ts`. Consumers of `listMemories` are the frozen
 * snapshot baking (`team/memory-snapshot.ts`) and the `memory` tool's
 * replace/remove old_text location (memory-mcp.ts); both receive
 * `{memory_id, content}` — the memory_id stays internal, never exposed to
 * the LLM (FR-008/FR-011).
 *
 * Structure mirrors `prompt-client.ts` (keepalive / round_robin / TLS
 * channel options, DI seam): the shared channel constants and the proto
 * path/options are imported from prompt-client to keep a single source of
 * truth for the keepalive policy and the proto loader configuration.
 */
import * as grpc from "@grpc/grpc-js";
import * as protoLoader from "@grpc/proto-loader";
import {
  registerDominionResolver,
} from "@dominion/common-js-grpc-resolver";
import { error } from "@dominion/common-js-logs";
import {
  PROTO_PATH,
  PROTO_OPTIONS,
  buildClientCredentials,
  buildChannelOptions,
  probeChannel,
} from "./prompt-client";

/** Dominion resolver target for the memory service. */
export const MEMORY_SERVICE_TARGET = "dominion:///game/memory:50051";

/**
 * One memory entry as returned by `listMemories`: the service's internal
 * resource id (memory_id) plus the entry text. The memory_id is used only
 * for internal location (replace/remove old_text matching, snapshot
 * refresh) and MUST NOT be rendered into LLM-visible text (FR-008/FR-011).
 */
export interface MemoryEntry {
	memory_id: string;
	content: string;
}

/**
 * Build a Memory resource name (AIP-122, contract §3):
 * `templates/{template}/sessions/{session}/memories/{memoryId}`.
 */
export function memoryName(
	template: string,
	session: string,
	memoryId: string,
): string {
	return `templates/${template}/sessions/${session}/memories/${memoryId}`;
}

/**
 * Client for the MemoryService gRPC API.
 *
 * Registers the dominion resolver on construction, loads the game.proto
 * definition, and creates a service-specific gRPC client that resolves
 * the memory service endpoint via the dominion URI scheme (same wiring as
 * `prompt-client.ts`).
 *
 * The optional `client` parameter allows dependency injection of a mock
 * client for testing without a live gRPC connection (DI seam,
 * `style/javascript.md` §测试 — no `vi.mock`).
 */
export class MemoryClient {
	private client: grpc.Client;

	/**
	 * @param client Optional pre-configured gRPC client (for testing).
	 *
	 * `registerDominionResolver` is only invoked on the real-construction
	 * path (no injected client) — an injected client already owns its
	 * channel, so it neither needs the dominion URI resolver nor the
	 * proto-loader/fs side effects.
	 */
	constructor(client?: grpc.Client) {
		if (client) {
			this.client = client;
		} else {
			registerDominionResolver();

			const packageDefinition = protoLoader.loadSync(
				PROTO_PATH,
				PROTO_OPTIONS,
			);
			const proto = grpc.loadPackageDefinition(
				packageDefinition,
			) as Record<string, unknown>;
			const memorySvc = (proto as any).projects.game.MemoryService;
			this.client = new memorySvc(
				MEMORY_SERVICE_TARGET,
				buildClientCredentials(),
				buildChannelOptions(),
			);
		}
	}

	/**
	 * Create a memory entry under a session (AIP-133).
	 *
	 * The request carries the resource EMBEDDED — `memory_id` (the
	 * service-internal storage key, generated by the agent on add) plus the
	 * `Memory` body `{name, content}` (contract §3; Phase 1/3 request-shape
	 * correction — content lives on `memory.content`, not top-level).
	 *
	 * @throws {grpc.ServiceError} Propagates gRPC errors from the service
	 *   (ALREADY_EXISTS when the memory_id collides — callers dedupe first).
	 */
	async createMemory(
		template: string,
		session: string,
		memoryId: string,
		content: string,
	): Promise<void> {
		const name = memoryName(template, session, memoryId);
		await this.call<void>((client, metadata, options, cb) =>
			(client as any).createMemory(
				{
					parent: `templates/${template}/sessions/${session}`,
					memoryId,
					memory: { name, content },
				},
				metadata,
				options,
				cb,
			),
		);
	}

	/**
	 * Update a memory entry's content (AIP-134).
	 *
	 * The request is `Memory{name, content}` + a `FieldMask` whose only path
	 * is `"content"` — the sole mutable Memory field (contract §3; Phase 1/3
	 * request-shape correction).
	 *
	 * @throws {grpc.ServiceError} NOT_FOUND when the memory does not exist.
	 */
	async updateMemory(
		template: string,
		session: string,
		memoryId: string,
		content: string,
	): Promise<void> {
		await this.call<void>((client, metadata, options, cb) =>
			(client as any).updateMemory(
				{
					memory: {
						name: memoryName(template, session, memoryId),
						content,
					},
					updateMask: { paths: ["content"] },
				},
				metadata,
				options,
				cb,
			),
		);
	}

	/**
	 * Delete a memory entry (AIP-135).
	 *
	 * @throws {grpc.ServiceError} NOT_FOUND when the memory does not exist.
	 */
	async deleteMemory(
		template: string,
		session: string,
		memoryId: string,
	): Promise<void> {
		await this.call<void>((client, metadata, options, cb) =>
			(client as any).deleteMemory(
				{ name: memoryName(template, session, memoryId) },
				metadata,
				options,
				cb,
			),
		);
	}

	/**
	 * List all memory entries under a session (AIP-132/AIP-158), walking
	 * every page until `next_page_token` is empty.
	 *
	 * Returns `{memory_id, content}[]` — the memory_id for internal
	 * location only (frozen-snapshot refresh, memory-tool old_text
	 * matching); it must never be rendered to the LLM (FR-011).
	 *
	 * @throws {grpc.ServiceError} Propagates gRPC errors from the service.
	 */
	async listMemories(
		template: string,
		session: string,
	): Promise<MemoryEntry[]> {
		const parent = `templates/${template}/sessions/${session}`;
		const entries: MemoryEntry[] = [];
		let pageToken = "";
		do {
			const response = await this.call<{
				memories: Array<{ memoryId?: string; content?: string }>;
				nextPageToken?: string;
			}>((client, metadata, options, cb) =>
				(client as any).listMemories(
					{ parent, pageToken: pageToken || undefined },
					metadata,
					options,
					cb,
				),
			);
			for (const m of (response?.memories ?? []) as Array<{
				memoryId?: string;
				content?: string;
			}>) {
				if (m.memoryId != null && m.content != null) {
					entries.push({ memory_id: m.memoryId, content: m.content });
				}
			}
			pageToken = response?.nextPageToken ?? "";
		} while (pageToken.length > 0);
		return entries;
	}

	/** Close the underlying gRPC client connection. */
	close(): void {
		this.client.close();
	}

	/**
	 * Shared callback-style RPC invocation (same shape as prompt-client's
	 * getTeamProfile: request + Metadata({waitForReady:true}) + deadline).
	 *
	 * @param invoke `(client, metadata, options, callback) => void`
	 * @returns The RPC response.
	 */
	private call<T>(
		invoke: (
			client: grpc.Client,
			metadata: grpc.Metadata,
			options: { deadline: Date },
			callback: (err: grpc.ServiceError | null, response?: T) => void,
		) => void,
	): Promise<T> {
		return new Promise<T>((resolve, reject) => {
			const deadline = new Date();
			deadline.setSeconds(deadline.getSeconds() + 10);
			// Probe-and-nudge the channel (forces IDLE→CONNECTING; logs state
			// for diagnosis — see probeChannel in prompt-client.ts): a
			// connection drop must not leave the channel permanently stuck in
			// "Waiting for LB pick".
			probeChannel(this.client, "memory client call");
			invoke(
				this.client,
				new grpc.Metadata({ waitForReady: true }),
				{ deadline },
				(err: grpc.ServiceError | null, response?: T) => {
					if (err) {
						error("memory client call failed", {
							error: err.message,
							code: String(err.code),
							channelState: probeChannel(
								this.client,
								"memory client call (after failure)",
							),
						});
						reject(err);
						return;
					}
					resolve(response as T);
				},
			);
		});
	}
}
