/**
 * Spike T001 — verify research.md D2.
 *
 * Hypothesis (specs/023-saolei-mcp-refine/research.md D2): a LangChain
 * `tool()` function, when invoked by the `createAgent` ToolNode, receives
 * the originating tool-call id on its `RunnableConfig` at
 * `config.toolCall.id`, and that id equals `AIMessage.tool_calls[0].id` —
 * the same id LangChain assigns on the model's tool-call message.
 *
 * Source-of-truth for the field path:
 *   langchain-ai/langchainjs `libs/langchain-core/src/tools/utils.ts` — the
 *   `_configHasToolCallId` type guard reads `config.toolCall.id`
 *   (https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-core/src/tools/utils.ts).
 *
 * Pinned runtime: `@langchain/langgraph` ^1.4.8 / `langchain` ^1.5.3
 * (pnpm-workspace.yaml catalog). If the field is absent or shaped differently
 * under these versions, D2 is falsified — STOP and report (do not work around).
 *
 * The tool id threading underpins contracts/tool-dispatch-contract.md §1..§2
 * (each tool reads `config.toolCall?.id` and passes it to
 * `OperationBridge.dispatch(part, toolId, signal)`).
 */

import { describe, expect, it, vi } from "vitest";

import { AIMessage, HumanMessage } from "@langchain/core/messages";
import { fakeModel } from "@langchain/core/testing";
import { MemorySaver } from "@langchain/langgraph";
import { createAgent, tool } from "langchain";
import { z } from "zod";

describe("D2: config.toolCall.id threads from AIMessage.tool_calls into the tool", () => {
  it("exposes config.toolCall.id equal to AIMessage.tool_calls[0].id", async () => {
    // DI seam: capture the config the ToolNode hands to the tool function.
    // Per style/javascript.md §Mock, use a vi.fn() test-double (no vi.mock).
    const captureConfig = vi.fn();
    const probe = tool(
      async (_args, config) => {
        captureConfig(config);
        return "ok";
      },
      {
        name: "probe",
        description: "spike probe",
        schema: z.object({ x: z.number() }),
      },
    );

    // First invocation → AIMessage with tool_calls (id auto-generated by
    // fakeModel.respondWithTools); second invocation → plain AIMessage that
    // ends the agent loop. FIFO, one response per invoke (fake_model_builder.d.ts).
    const model = fakeModel()
      .respondWithTools([{ name: "probe", args: { x: 1 } }])
      .respond(new AIMessage("done"));

    const agent = createAgent({
      model,
      tools: [probe],
      checkpointer: new MemorySaver(),
    });

    const result = (await agent.invoke(
      { messages: [new HumanMessage("call probe")] },
      { configurable: { thread_id: "spike-d2" } },
    )) as {
      messages: Array<{
        tool_calls?: Array<{ id?: string; name?: string; args?: unknown }>;
      }>;
    };

    // Gate: the tool was exercised exactly once (style/javascript.md — verify
    // the captured seam fired; a silently-uncalled tool would make the rest
    // vacuous). Asserting exactly-once fail-fasts if a future LangChain version
    // invokes the tool multiple times, which would otherwise be masked by
    // reading calls[0][0] below.
    expect(captureConfig).toHaveBeenCalledTimes(1);

    // Locate the AIMessage the model emitted carrying tool_calls — its
    // tool_calls[0].id is the value LangChain should thread onto config.toolCall.id.
    const aiWithTools = result.messages.find(
      (m) => Array.isArray(m.tool_calls) && m.tool_calls.length > 0,
    );
    expect(aiWithTools).toBeDefined();
    const expectedId = aiWithTools!.tool_calls![0].id;
    expect(typeof expectedId).toBe("string");
    expect(expectedId!.length).toBeGreaterThan(0);

    // Core D2 assertion: config.toolCall.id exists and matches tool_calls[0].id.
    const captured = captureConfig.mock.calls[0][0] as {
      toolCall?: { id?: string };
      toolCallId?: string;
    };
    const configToolCallId = captured?.toolCall?.id;
    expect(configToolCallId).toBeDefined();
    expect(typeof configToolCallId).toBe("string");
    expect(configToolCallId).toBe(expectedId);

    // Diagnostic: also surface config.toolCallId (the ToolRuntime convenience
    // alias) so a future LangChain rename is visible without re-derivation.
    // Not asserted — D2's contract path is config.toolCall.id.
    // eslint-disable-next-line no-console
    console.warn(
      "[spike.toolcall D2] config.toolCall.id=",
      configToolCallId,
      "| config.toolCallId=",
      captured?.toolCallId,
    );
  });
});
