version: "3.0"
name: runtime
app: game
desc: game runtime service
kind: stateful
exposure: aggregate
artifacts:
  - name: cmd
    target: app/cmd:cmd_image
    tls: true
    ports:
      - name: http
        port: 8080
      - name: grpc
        port: 8082
