load("@rules_go//go:def.bzl", "go_library")
load("//tools/dev/go:defs.bzl", "go_unittest")

go_library(
    name = "service",
    srcs = ["service.go"],
    importpath = "dominion/projects/game/proxy/service",
    visibility = ["//visibility:public"],
    deps = [
        "//common/gopkg/logs",
        "//common/gopkg/logs/event",
        "//projects/game",
        "//projects/game/pkg/bind",
        "//projects/game/proxy/domain",
        "//projects/game/proxy/runtime/agentclient",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)

go_unittest(
    name = "service_test",
    srcs = ["service_test.go"],
    embed = [":service"],
    deps = [
        "//projects/game",
        "//projects/game/pkg/bind",
        "//projects/game/proxy/domain",
        "//projects/game/proxy/runtime/agentclient",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//metadata",
        "@org_golang_google_grpc//status",
    ],
)
