name: service
app: deploy
desc: deploy service
artifacts:
  - name: service
    type: deployment
    target: app/cmd:deploy_image
    tls: false
    ports:
      - name: grpc
        port: 8080
      - name: http
        port: 8081
  - name: service-iface
    type: deployment
    target: app/iface:deploy_iface_image
    tls: false
    ports:
      - name: grpc
        port: 8080
      - name: http
        port: 8081
