load("@rules_go//go:def.bzl", "go_library")
load("//tools/dev/go:defs.bzl", "go_unittest")

go_library(
    name = "service",
    srcs = [
        "control.go",
        "runtime.go",
        "worker.go",
    ],
    importpath = "dominion/projects/game/runtime/service",
    visibility = ["//visibility:public"],
    deps = [
        "//common/gopkg/bootstrap",
        "//common/gopkg/logs",
        "//common/gopkg/logs/event",
        "//common/gopkg/otel",
        "//projects/game/pkg/token",
        "//projects/game/runtime/config",
        "//projects/game/runtime/domain",
        "//projects/game/runtime/domain/mediacache",
        "//projects/game/runtime/domain/sessionmanager",
    ],
)

go_unittest(
    name = "service_test",
    srcs = [
        "control_test.go",
        "runtime_test.go",
    ],
    embed = [":service"],
    deps = [
        "//projects/game/pkg/token",
        "//projects/game/runtime/config",
        "//projects/game/runtime/domain",
        "//projects/game/runtime/domain/sessionmanager",
    ],
)
