load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("//tools/release:defs.bzl", "artifact_image")

go_library(
    name = "cmd_lib",
    srcs = ["main.go"],
    importpath = "dominion/projects/game/gateway/app/cmd",
    visibility = ["//visibility:private"],
    deps = [
        "//common/gopkg/bootstrap",
        "//common/gopkg/grpc",
        "//common/gopkg/grpc/solver",
        "//common/gopkg/http",
        "//common/gopkg/otel",
        "//projects/game/gateway/app",
        "//projects/game/gateway/runtime/owner",
        "//projects/game/pkg/const",
        "//projects/game/pkg/token",
        "//projects/game/runtime",
        "//projects/game/session",
        "@grpc_ecosystem_grpc_gateway//runtime",
        "@org_golang_google_grpc//:grpc",
    ],
)

go_binary(
    name = "cmd",
    embed = [":cmd_lib"],
    visibility = ["//visibility:public"],
)

artifact_image(
    name = "cmd_image",
    app = "game",
    binary = ":cmd",
    service = "gateway",
)
