load("@rules_go//go:def.bzl", "go_library")
load("//tools/dev/go:defs.bzl", "go_unittest")

go_library(
    name = "operation",
    srcs = [
        "convert.go",
        "cursor.go",
        "execute_other.go",
        "execute_v2.go",
        "execute_v2_logic.go",
        "execute_v2_other.go",
        "execute_window_message.go",
        "execute_window_message_other.go",
        "execute_windows.go",
    ],
    importpath = "dominion/projects/game/desktop/internal/operation",
    visibility = ["//projects/game/desktop:__subpackages__"],
    deps = ["//projects/game"],
)

go_unittest(
    name = "operation_test",
    srcs = [
        "convert_test.go",
        "cursor_test.go",
        "execute_v2_other_test.go",
        "execute_v2_test.go",
        "execute_window_message_test.go",
        "execute_windows_test.go",
    ],
    embed = [":operation"],
    deps = ["//projects/game"],
)
