package operation

import (
	"fmt"

	"dominion/projects/game"
)

// Win32 WM_* mouse-button message constants. The values are plain integers
// matching the Win32 API and are only consumed by PostMessage on Windows;
// declaring them here keeps the action-sequence logic compilable and
// unit-testable on every platform (same pattern as the v2 MOUSEEVENTF_*
// constants in execute_v2_logic.go).
//
// Ref: https://learn.microsoft.com/en-us/windows/win32/inputdev/mouse-input-notifications
const (
	wmMouseMove     = 0x0200
	wmLButtonDown   = 0x0201
	wmLButtonUp     = 0x0202
	wmLButtonDblClk = 0x0203
	wmRButtonDown   = 0x0204
	wmRButtonUp     = 0x0205
	wmRButtonDblClk = 0x0206
)

// Win32 keyboard message constants and the VK_F2 virtual-key code.
//
// Ref: https://learn.microsoft.com/en-us/windows/win32/inputdev/keyboard-input-notifications
// Ref: https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
const (
	wmKeyDown = 0x0100
	wmKeyUp   = 0x0101
	vkF2      = 0x71
)

// makeLPARAM packs two signed client coordinates into a Win32 LPARAM the way
// the MAKELPARAM macro does: low-order word = x, high-order word = y. The
// client coordinates are signed (multi-monitor systems can have negative
// client coordinates), so each lane is width-masked to a 16-bit value before
// packing to preserve the wrap-around semantics Win32 expects.
//
// Used to build the lParam for WM_LBUTTONDOWN/WM_RBUTTONDOWN/... per the
// "Desktop MouseClickAction → WM_* mapping" table in
// specs/018-saolei-mcp/contracts/proto-operation-contract.md (FR-004d).
//
// Ref: https://learn.microsoft.com/en-us/windows/win32/inputdev/wm-lbuttondown
func makeLPARAM(x, y int32) uintptr {
	return uintptr(uint16(x)) | (uintptr(uint16(y)) << 16)
}

// wmMessageSequence returns the ordered Win32 WM_* button messages for the
// given click action. Each entry produces one PostMessage call dispatched by
// the Windows caller; the contract requires only that the down/up messages
// reach the target coordinate without OS cursor movement.
//
// LEFT_RIGHT_PRESS order is left-down, right-down, right-up, left-up,
// modeling a single simultaneous left+right press (a chord) per the contract
// (specs/018-saolei-mcp/contracts/proto-operation-contract.md).
//
// The double-click variants do NOT emit WM_LBUTTONDBLCLK / WM_RBUTTONDBLCLK:
// those are only generated by the system when the window has CS_DBLCLKS and
// the user produces a real double-click. Posted messages have no such
// detection, so two down/up cycles is the closest a posting client can get.
func wmMessageSequence(action game.MouseClickAction) ([]uint32, error) {
	switch action {
	case game.MouseClickAction_MOUSE_CLICK_ACTION_LEFT_CLICK:
		return []uint32{wmLButtonDown, wmLButtonUp}, nil
	case game.MouseClickAction_MOUSE_CLICK_ACTION_LEFT_DOUBLE_CLICK:
		return []uint32{wmLButtonDown, wmLButtonUp, wmLButtonDown, wmLButtonUp}, nil
	case game.MouseClickAction_MOUSE_CLICK_ACTION_RIGHT_CLICK:
		return []uint32{wmRButtonDown, wmRButtonUp}, nil
	case game.MouseClickAction_MOUSE_CLICK_ACTION_RIGHT_DOUBLE_CLICK:
		return []uint32{wmRButtonDown, wmRButtonUp, wmRButtonDown, wmRButtonUp}, nil
	case game.MouseClickAction_MOUSE_CLICK_ACTION_LEFT_RIGHT_PRESS:
		return []uint32{wmLButtonDown, wmRButtonDown, wmRButtonUp, wmLButtonUp}, nil
	default:
		return nil, fmt.Errorf("unsupported click action: %v", action)
	}
}

// keyboardKeyToVK maps a proto KeyboardKey enum value to its Win32 virtual-key
// code. Only KeyboardKey_KEYBOARD_KEY_F2 is currently defined; new keys must
// be added here as the proto enum grows.
func keyboardKeyToVK(key game.KeyboardKey) (uint32, error) {
	switch key {
	case game.KeyboardKey_KEYBOARD_KEY_F2:
		return vkF2, nil
	default:
		return 0, fmt.Errorf("unsupported keyboard key: %v", key)
	}
}

// EffectiveMethod returns the MouseInputMethod the desktop should actually
// execute. UNSPECIFIED collapses to SIMULATED so legacy mouse Parts (whose
// new method field defaults to UNSPECIFIED) keep their prior behavior
// (spec 018-saolei-mcp FR-004c; AIP-180 backward compatibility).
func EffectiveMethod(m game.MouseInputMethod) game.MouseInputMethod {
	if m == game.MouseInputMethod_MOUSE_INPUT_METHOD_UNSPECIFIED {
		return game.MouseInputMethod_MOUSE_INPUT_METHOD_SIMULATED
	}
	return m
}
