load("@rules_go//go:def.bzl", "go_library")
load("//tools/dev/go:defs.bzl", "go_unittest")

go_library(
    name = "api",
    srcs = [
        "client.go",
        "models.go",
        "websocket.go",
    ],
    importpath = "dominion/projects/game/desktop/internal/api",
    visibility = ["//projects/game/desktop:__subpackages__"],
    deps = ["@com_github_coder_websocket//:websocket"],
)

go_unittest(
    name = "api_test",
    srcs = [
        "client_test.go",
        "websocket_test.go",
    ],
    embed = [":api"],
    deps = ["@com_github_coder_websocket//:websocket"],
)
