load("@rules_go//go:def.bzl", "go_library")
load("//tools/dev/go:defs.bzl", "go_unittest")

go_library(
    name = "api",
    srcs = [
        "client.go",
        "websocket.go",
    ],
    importpath = "dominion/projects/game/desktop/internal/api",
    visibility = ["//projects/game/desktop:__subpackages__"],
    deps = [
        "//projects/game",
        "//projects/game/desktop/internal/trace",
        "@com_github_coder_websocket//:websocket",
        "@org_golang_google_protobuf//encoding/protojson",
    ],
)

go_unittest(
    name = "api_test",
    srcs = [
        "client_test.go",
        "websocket_test.go",
    ],
    embed = [":api"],
    deps = [
        "//common/gopkg/otel/tracecontext",
        "//projects/game",
        "@com_github_coder_websocket//:websocket",
        "@org_golang_google_protobuf//encoding/protojson",
    ],
)
