package api

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"strings"

	game "dominion/projects/game"
	"dominion/projects/game/desktop/internal/trace"

	"google.golang.org/protobuf/encoding/protojson"
)

// Config holds the desktop client configuration.
type Config struct {
	GatewayURL string `json:"gateway_url"`
	Env        string `json:"env,omitempty"`
}

// Client is an HTTP client for the game gateway REST API.
type Client struct {
	cfg  Config
	http *http.Client
}

// NewClient creates a new Client with the given config.
func NewClient(cfg Config) *Client {
	return &Client{
		cfg:  cfg,
		http: &http.Client{Transport: trace.NewHTTPTransport()},
	}
}

// url constructs a full URL from the config's GatewayURL and the given path.
// It strips any trailing slash from GatewayURL before appending the path.
func (c *Client) url(path string) string {
	return strings.TrimSuffix(c.cfg.GatewayURL, "/") + path
}

// newRequest builds an http.Request with context, method, path, and body,
// setting common headers (Content-Type, and env if configured).
func (c *Client) newRequest(ctx context.Context, method, path string, body io.Reader) (*http.Request, error) {
	req, err := http.NewRequestWithContext(ctx, method, c.url(path), body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	if c.cfg.Env != "" {
		req.Header.Set("env", c.cfg.Env)
	}
	return req, nil
}

// CreateSession creates a new game session via POST to /api/v1/sessions.
// The session ID is generated by the server — no session_id is sent in the request.
func (c *Client) CreateSession(ctx context.Context) (*game.Session, error) {
	body, err := protojson.Marshal(new(game.CreateSessionRequest))
	if err != nil {
		return nil, fmt.Errorf("create session: %w", err)
	}

	req, err := c.newRequest(ctx, http.MethodPost, "/api/v1/sessions", bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("create session: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("create session: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("create session: status %d: %s", resp.StatusCode, string(respBody))
	}

	session := new(game.Session)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, session); err != nil {
		return nil, fmt.Errorf("create session: %w", err)
	}
	return session, nil
}

// ListSessions lists all sessions via GET to /api/v1/sessions.
// Query parameters page_size and page_token control pagination.
func (c *Client) ListSessions(ctx context.Context, pageSize int32, pageToken string) (*game.ListSessionsResponse, error) {
	path := "/api/v1/sessions"
	params := []string{}
	if pageSize > 0 {
		params = append(params, fmt.Sprintf("page_size=%d", pageSize))
	}
	if pageToken != "" {
		params = append(params, fmt.Sprintf("page_token=%s", pageToken))
	}
	if len(params) > 0 {
		path += "?" + strings.Join(params, "&")
	}

	req, err := c.newRequest(ctx, http.MethodGet, path, nil)
	if err != nil {
		return nil, fmt.Errorf("list sessions: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("list sessions: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("list sessions: status %d: %s", resp.StatusCode, string(respBody))
	}

	result := new(game.ListSessionsResponse)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, result); err != nil {
		return nil, fmt.Errorf("list sessions: %w", err)
	}
	return result, nil
}

// GetSession retrieves a session by ID via GET to /api/v1/sessions/{sessionID}.
func (c *Client) GetSession(ctx context.Context, sessionID string) (*game.Session, error) {
	req, err := c.newRequest(ctx, http.MethodGet, "/api/v1/sessions/"+sessionID, nil)
	if err != nil {
		return nil, fmt.Errorf("get session: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("get session: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("get session: status %d: %s", resp.StatusCode, string(respBody))
	}

	session := new(game.Session)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, session); err != nil {
		return nil, fmt.Errorf("get session: %w", err)
	}
	return session, nil
}

// DeleteSession deletes a session by ID via DELETE to /api/v1/sessions/{sessionID}.
func (c *Client) DeleteSession(ctx context.Context, sessionID string) error {
	req, err := c.newRequest(ctx, http.MethodDelete, "/api/v1/sessions/"+sessionID, nil)
	if err != nil {
		return fmt.Errorf("delete session: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("delete session: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("delete session: status %d: %s", resp.StatusCode, string(respBody))
	}
	return nil
}

// ListAgentProfiles lists agent profiles via GET to /api/v1/prompts/agentProfiles.
func (c *Client) ListAgentProfiles(ctx context.Context, pageSize int32, pageToken string) (*game.ListAgentProfilesResponse, error) {
	path := "/api/v1/prompts/agentProfiles"
	params := []string{}
	if pageSize > 0 {
		params = append(params, fmt.Sprintf("page_size=%d", pageSize))
	}
	if pageToken != "" {
		params = append(params, fmt.Sprintf("page_token=%s", pageToken))
	}
	if len(params) > 0 {
		path += "?" + strings.Join(params, "&")
	}

	req, err := c.newRequest(ctx, http.MethodGet, path, nil)
	if err != nil {
		return nil, fmt.Errorf("list agent profiles: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("list agent profiles: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("list agent profiles: status %d: %s", resp.StatusCode, string(respBody))
	}

	result := new(game.ListAgentProfilesResponse)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, result); err != nil {
		return nil, fmt.Errorf("list agent profiles: %w", err)
	}
	return result, nil
}

// GetAgent retrieves the agent for a session via GET to /api/v1/sessions/{sessionID}/agent.
func (c *Client) GetAgent(ctx context.Context, sessionID string) (*game.Agent, error) {
	req, err := c.newRequest(ctx, http.MethodGet, "/api/v1/sessions/"+sessionID+"/agent", nil)
	if err != nil {
		return nil, fmt.Errorf("get agent: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("get agent: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("get agent: status %d: %s", resp.StatusCode, string(respBody))
	}

	agent := new(game.Agent)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, agent); err != nil {
		return nil, fmt.Errorf("get agent: %w", err)
	}
	return agent, nil
}

// ListMessages lists all messages for a session via GET to
// /api/v1/sessions/{sessionID}/messages.
func (c *Client) ListMessages(ctx context.Context, sessionID string) (*game.ListMessagesResponse, error) {
	req, err := c.newRequest(ctx, http.MethodGet, "/api/v1/sessions/"+sessionID+"/messages", nil)
	if err != nil {
		return nil, fmt.Errorf("list messages: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("list messages: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("list messages: status %d: %s", resp.StatusCode, string(respBody))
	}

	result := new(game.ListMessagesResponse)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, result); err != nil {
		return nil, fmt.Errorf("list messages: %w", err)
	}
	return result, nil
}

// CreateAgentProfile creates an agent profile via POST to /api/v1/prompts/agentProfiles.
func (c *Client) CreateAgentProfile(ctx context.Context, req *game.CreateAgentProfileRequest) (*game.AgentProfile, error) {
	body, err := protojson.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("create agent profile: %w", err)
	}

	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/v1/prompts/agentProfiles", bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("create agent profile: %w", err)
	}

	resp, err := c.http.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("create agent profile: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("create agent profile: status %d: %s", resp.StatusCode, string(respBody))
	}

	profile := new(game.AgentProfile)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, profile); err != nil {
		return nil, fmt.Errorf("create agent profile: %w", err)
	}
	return profile, nil
}

// GetAgentProfile retrieves an agent profile via GET to /api/v1/prompts/agentProfiles/{agentProfileName}.
func (c *Client) GetAgentProfile(ctx context.Context, agentProfileName string) (*game.AgentProfile, error) {
	req, err := c.newRequest(ctx, http.MethodGet, "/api/v1/prompts/agentProfiles/"+agentProfileName, nil)
	if err != nil {
		return nil, fmt.Errorf("get agent profile: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("get agent profile: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("get agent profile: status %d: %s", resp.StatusCode, string(respBody))
	}

	profile := new(game.AgentProfile)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, profile); err != nil {
		return nil, fmt.Errorf("get agent profile: %w", err)
	}
	return profile, nil
}

// DeleteAgentProfile deletes an agent profile via DELETE to /api/v1/prompts/agentProfiles/{agentProfileName}.
func (c *Client) DeleteAgentProfile(ctx context.Context, agentProfileName string) error {
	req, err := c.newRequest(ctx, http.MethodDelete, "/api/v1/prompts/agentProfiles/"+agentProfileName, nil)
	if err != nil {
		return fmt.Errorf("delete agent profile: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("delete agent profile: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("delete agent profile: status %d: %s", resp.StatusCode, string(respBody))
	}
	return nil
}

// UpdateAgentProfile partially updates an agent profile via PATCH to
// /api/v1/prompts/agentProfiles/{agentProfileName}. The update_mask paths are
// sent as the repeated update_mask.paths query parameter per grpc-gateway
// FieldMask binding.
func (c *Client) UpdateAgentProfile(ctx context.Context, agentProfileName string, profile *game.AgentProfile, updateMaskPaths []string) (*game.AgentProfile, error) {
	body, err := (protojson.MarshalOptions{EmitUnpopulated: false}).Marshal(profile)
	if err != nil {
		return nil, fmt.Errorf("update agent profile: %w", err)
	}

	path := "/api/v1/prompts/agentProfiles/" + agentProfileName
	if len(updateMaskPaths) > 0 {
		path += "?update_mask=" + strings.Join(updateMaskPaths, ",")
	}

	httpReq, err := c.newRequest(ctx, http.MethodPatch, path, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("update agent profile: %w", err)
	}

	resp, err := c.http.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("update agent profile: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("update agent profile: status %d: %s", resp.StatusCode, string(respBody))
	}

	updated := new(game.AgentProfile)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, updated); err != nil {
		return nil, fmt.Errorf("update agent profile: %w", err)
	}
	return updated, nil
}

// RefreshAgent refreshes the agent for a session via POST to
// /api/v1/sessions/{sessionID}/agent:refresh. Used after a profile update so
// the agent reloads its adapter with the new configuration.
func (c *Client) RefreshAgent(ctx context.Context, sessionID string) error {
	req, err := c.newRequest(ctx, http.MethodPost, "/api/v1/sessions/"+sessionID+"/agent:refresh", bytes.NewReader([]byte(`{}`)))
	if err != nil {
		return fmt.Errorf("refresh agent: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("refresh agent: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("refresh agent: status %d: %s", resp.StatusCode, string(respBody))
	}
	return nil
}
