package api

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	game "dominion/projects/game"
	"dominion/projects/game/desktop/internal/trace"

	"google.golang.org/protobuf/encoding/protojson"
)

// Config holds the desktop client configuration.
type Config struct {
	GatewayURL string `json:"gateway_url"`
	Env        string `json:"env,omitempty"`
}

// Client is an HTTP client for the game gateway REST API.
type Client struct {
	cfg  Config
	http *http.Client
}

// NewClient creates a new Client with the given config.
func NewClient(cfg Config) *Client {
	return &Client{
		cfg:  cfg,
		http: &http.Client{Transport: trace.NewHTTPTransport()},
	}
}

// url constructs a full URL from the config's GatewayURL and the given path.
// It strips any trailing slash from GatewayURL before appending the path.
func (c *Client) url(path string) string {
	return strings.TrimSuffix(c.cfg.GatewayURL, "/") + path
}

// newRequest builds an http.Request with context, method, path, and body,
// setting common headers (Content-Type, and env if configured).
func (c *Client) newRequest(ctx context.Context, method, path string, body io.Reader) (*http.Request, error) {
	req, err := http.NewRequestWithContext(ctx, method, c.url(path), body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	if c.cfg.Env != "" {
		req.Header.Set("env", c.cfg.Env)
	}
	return req, nil
}

// templatePath prefixes a REST path with the template segment. template is
// the Template path segment (e.g. "saolei" — the Template resource name
// "templates/{template}" without the "templates/" prefix; AIP-122, spec
// 031-team-template-mode contracts/api-contract.md §1). It escapes the
// segment so a malicious/garbage template cannot inject path separators.
func templatePath(template, suffix string) string {
	return "/api/v1/templates/" + url.PathEscape(template) + suffix
}

// CreateSession creates a new game session under a template via POST to
// /api/v1/templates/{template}/sessions (AIP-133; game.proto
// SessionService.CreateSession). The session ID is generated by the server —
// no session_id is sent in the request.
func (c *Client) CreateSession(ctx context.Context, template string) (*game.Session, error) {
	body, err := protojson.Marshal(new(game.CreateSessionRequest))
	if err != nil {
		return nil, fmt.Errorf("create session: %w", err)
	}

	req, err := c.newRequest(ctx, http.MethodPost, templatePath(template, "/sessions"), bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("create session: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("create session: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("create session: status %d: %s", resp.StatusCode, string(respBody))
	}

	session := new(game.Session)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, session); err != nil {
		return nil, fmt.Errorf("create session: %w", err)
	}
	return session, nil
}

// ListSessions lists sessions under a template via GET to
// /api/v1/templates/{template}/sessions (AIP-132). Query parameters
// page_size and page_token control pagination.
func (c *Client) ListSessions(ctx context.Context, template string, pageSize int32, pageToken string) (*game.ListSessionsResponse, error) {
	q := url.Values{}
	if pageSize > 0 {
		q.Set("page_size", fmt.Sprintf("%d", pageSize))
	}
	if pageToken != "" {
		q.Set("page_token", pageToken)
	}
	u := &url.URL{Path: templatePath(template, "/sessions"), RawQuery: q.Encode()}

	req, err := c.newRequest(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("list sessions: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("list sessions: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("list sessions: status %d: %s", resp.StatusCode, string(respBody))
	}

	result := new(game.ListSessionsResponse)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, result); err != nil {
		return nil, fmt.Errorf("list sessions: %w", err)
	}
	return result, nil
}

// GetSession retrieves a session by ID via GET to
// /api/v1/templates/{template}/sessions/{sessionID} (AIP-131).
func (c *Client) GetSession(ctx context.Context, template, sessionID string) (*game.Session, error) {
	path, err := url.JoinPath(templatePath(template, "/sessions"), sessionID)
	if err != nil {
		return nil, fmt.Errorf("get session: %w", err)
	}

	req, err := c.newRequest(ctx, http.MethodGet, path, nil)
	if err != nil {
		return nil, fmt.Errorf("get session: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("get session: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("get session: status %d: %s", resp.StatusCode, string(respBody))
	}

	session := new(game.Session)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, session); err != nil {
		return nil, fmt.Errorf("get session: %w", err)
	}
	return session, nil
}

// DeleteSession deletes a session by ID via DELETE to
// /api/v1/templates/{template}/sessions/{sessionID} (AIP-135).
func (c *Client) DeleteSession(ctx context.Context, template, sessionID string) error {
	path, err := url.JoinPath(templatePath(template, "/sessions"), sessionID)
	if err != nil {
		return fmt.Errorf("delete session: %w", err)
	}

	req, err := c.newRequest(ctx, http.MethodDelete, path, nil)
	if err != nil {
		return fmt.Errorf("delete session: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("delete session: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("delete session: status %d: %s", resp.StatusCode, string(respBody))
	}
	return nil
}

// GetTeam retrieves the Team of a session via GET to
// /api/v1/templates/{template}/sessions/{sessionID}/team (AIP-131;
// game.proto TeamService.GetTeam). The Team must already exist — it is
// created only by CreateTeam (no lazy creation, spec 031 design decision).
func (c *Client) GetTeam(ctx context.Context, template, sessionID string) (*game.Team, error) {
	path, err := url.JoinPath(templatePath(template, "/sessions"), sessionID, "team")
	if err != nil {
		return nil, fmt.Errorf("get team: %w", err)
	}

	req, err := c.newRequest(ctx, http.MethodGet, path, nil)
	if err != nil {
		return nil, fmt.Errorf("get team: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("get team: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("get team: status %d: %s", resp.StatusCode, string(respBody))
	}

	team := new(game.Team)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, team); err != nil {
		return nil, fmt.Errorf("get team: %w", err)
	}
	return team, nil
}

// CreateTeam creates the per-session singleton Team via POST to
// /api/v1/templates/{template}/sessions/{sessionID}/team (AIP-133;
// game.proto TeamService.CreateTeam). The request body carries the parent
// session and the TeamProfile full resource name
// (templates/{template}/profiles/{profile}); the server validates the
// profile's template segment against the parent (no implicit rules).
// profile is the TeamProfile resource name the team is built from.
func (c *Client) CreateTeam(ctx context.Context, template, sessionID, profile string) (*game.Team, error) {
	// Resource name construction is codegen-owned (spec 031-team-template-mode
	// contracts/api-contract.md §5): the parent Session resource name.
	parent := game.SessionName{TemplateID: template, SessionID: sessionID}.String()
	body, err := protojson.Marshal(&game.CreateTeamRequest{
		Parent:  parent,
		Profile: profile,
	})
	if err != nil {
		return nil, fmt.Errorf("create team: %w", err)
	}

	path, err := url.JoinPath(templatePath(template, "/sessions"), sessionID, "team")
	if err != nil {
		return nil, fmt.Errorf("create team: %w", err)
	}

	req, err := c.newRequest(ctx, http.MethodPost, path, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("create team: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("create team: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("create team: status %d: %s", resp.StatusCode, string(respBody))
	}

	team := new(game.Team)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, team); err != nil {
		return nil, fmt.Errorf("create team: %w", err)
	}
	return team, nil
}

// ListMessages lists messages of one team agent's partition via GET to
// /api/v1/templates/{template}/sessions/{sessionID}/team/agents/{agent}/messages
// (AIP-132; game.proto TeamService.ListMessages, FR-005). The Team must
// already exist.
func (c *Client) ListMessages(ctx context.Context, template, sessionID, agent string) (*game.ListMessagesResponse, error) {
	path, err := url.JoinPath(templatePath(template, "/sessions"), sessionID, "team", "agents", agent, "messages")
	if err != nil {
		return nil, fmt.Errorf("list messages: %w", err)
	}

	req, err := c.newRequest(ctx, http.MethodGet, path, nil)
	if err != nil {
		return nil, fmt.Errorf("list messages: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("list messages: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("list messages: status %d: %s", resp.StatusCode, string(respBody))
	}

	result := new(game.ListMessagesResponse)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, result); err != nil {
		return nil, fmt.Errorf("list messages: %w", err)
	}
	return result, nil
}

// RefreshTeam clears the session's short-term memory via POST to
// /api/v1/templates/{template}/sessions/{sessionID}/team:refresh (AIP-136
// custom method; game.proto TeamService.RefreshTeam, FR-018). The long-term
// strategy memory is unaffected.
func (c *Client) RefreshTeam(ctx context.Context, template, sessionID string) error {
	path, err := url.JoinPath(templatePath(template, "/sessions"), sessionID, "team:refresh")
	if err != nil {
		return fmt.Errorf("refresh team: %w", err)
	}

	req, err := c.newRequest(ctx, http.MethodPost, path, bytes.NewReader([]byte(`{}`)))
	if err != nil {
		return fmt.Errorf("refresh team: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("refresh team: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("refresh team: status %d: %s", resp.StatusCode, string(respBody))
	}
	return nil
}

// ListTeamProfiles lists TeamProfiles under a template via GET to
// /api/v1/templates/{template}/profiles (AIP-132; game.proto
// PromptService.ListTeamProfiles).
func (c *Client) ListTeamProfiles(ctx context.Context, template string, pageSize int32, pageToken string) (*game.ListTeamProfilesResponse, error) {
	q := url.Values{}
	if pageSize > 0 {
		q.Set("page_size", fmt.Sprintf("%d", pageSize))
	}
	if pageToken != "" {
		q.Set("page_token", pageToken)
	}
	u := &url.URL{Path: templatePath(template, "/profiles"), RawQuery: q.Encode()}

	req, err := c.newRequest(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("list team profiles: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("list team profiles: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("list team profiles: status %d: %s", resp.StatusCode, string(respBody))
	}

	result := new(game.ListTeamProfilesResponse)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, result); err != nil {
		return nil, fmt.Errorf("list team profiles: %w", err)
	}
	return result, nil
}

// CreateTeamProfile creates a TeamProfile via POST to
// /api/v1/templates/{template}/profiles (AIP-133; game.proto
// PromptService.CreateTeamProfile). Per the grpc-gateway body binding
// ("body: team_profile"), the HTTP body is the TeamProfile JSON (extracted
// from the request's team_profile field) while parent comes from the URI
// path and team_profile_id from the query string.
func (c *Client) CreateTeamProfile(ctx context.Context, template, profileID string, profile *game.TeamProfile) (*game.TeamProfile, error) {
	body, err := protojson.Marshal(profile)
	if err != nil {
		return nil, fmt.Errorf("create team profile: %w", err)
	}

	q := url.Values{}
	if profileID != "" {
		q.Set("team_profile_id", profileID)
	}
	u := &url.URL{Path: templatePath(template, "/profiles"), RawQuery: q.Encode()}

	httpReq, err := c.newRequest(ctx, http.MethodPost, u.String(), bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("create team profile: %w", err)
	}

	resp, err := c.http.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("create team profile: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("create team profile: status %d: %s", resp.StatusCode, string(respBody))
	}

	created := new(game.TeamProfile)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, created); err != nil {
		return nil, fmt.Errorf("create team profile: %w", err)
	}
	return created, nil
}

// GetTeamProfile retrieves a TeamProfile via GET to
// /api/v1/templates/{template}/profiles/{profileName} (AIP-131).
func (c *Client) GetTeamProfile(ctx context.Context, template, profileName string) (*game.TeamProfile, error) {
	path, err := url.JoinPath(templatePath(template, "/profiles"), profileName)
	if err != nil {
		return nil, fmt.Errorf("get team profile: %w", err)
	}

	req, err := c.newRequest(ctx, http.MethodGet, path, nil)
	if err != nil {
		return nil, fmt.Errorf("get team profile: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("get team profile: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("get team profile: status %d: %s", resp.StatusCode, string(respBody))
	}

	profile := new(game.TeamProfile)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, profile); err != nil {
		return nil, fmt.Errorf("get team profile: %w", err)
	}
	return profile, nil
}

// DeleteTeamProfile deletes a TeamProfile via DELETE to
// /api/v1/templates/{template}/profiles/{profileName} (AIP-135).
func (c *Client) DeleteTeamProfile(ctx context.Context, template, profileName string) error {
	path, err := url.JoinPath(templatePath(template, "/profiles"), profileName)
	if err != nil {
		return fmt.Errorf("delete team profile: %w", err)
	}

	req, err := c.newRequest(ctx, http.MethodDelete, path, nil)
	if err != nil {
		return fmt.Errorf("delete team profile: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("delete team profile: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("delete team profile: status %d: %s", resp.StatusCode, string(respBody))
	}
	return nil
}

// UpdateTeamProfile partially updates a TeamProfile via PATCH to
// /api/v1/templates/{template}/profiles/{profileName} (AIP-134; game.proto
// PromptService.UpdateTeamProfile). Per the grpc-gateway body binding
// ("body: team_profile" with path variable {team_profile.name}), the
// TeamProfile JSON is sent as the PATCH body with its name field set to the
// full resource name; update_mask paths are sent as the repeated
// update_mask.paths query parameter. The mask supports oneof-member paths
// (e.g. saolei.player_model / saolei.planner_model).
func (c *Client) UpdateTeamProfile(ctx context.Context, template, profileName string, profile *game.TeamProfile, updateMaskPaths []string) (*game.TeamProfile, error) {
	body, err := (protojson.MarshalOptions{EmitUnpopulated: false}).Marshal(profile)
	if err != nil {
		return nil, fmt.Errorf("update team profile: %w", err)
	}

	path, err := url.JoinPath(templatePath(template, "/profiles"), profileName)
	if err != nil {
		return nil, fmt.Errorf("update team profile: %w", err)
	}
	q := url.Values{}
	if len(updateMaskPaths) > 0 {
		q.Set("update_mask", strings.Join(updateMaskPaths, ","))
	}
	u := &url.URL{Path: path, RawQuery: q.Encode()}

	httpReq, err := c.newRequest(ctx, http.MethodPatch, u.String(), bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("update team profile: %w", err)
	}

	resp, err := c.http.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("update team profile: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("update team profile: status %d: %s", resp.StatusCode, string(respBody))
	}

	updated := new(game.TeamProfile)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, updated); err != nil {
		return nil, fmt.Errorf("update team profile: %w", err)
	}
	return updated, nil
}
