package api

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"strings"

	game "dominion/projects/game"
	"dominion/projects/game/desktop/internal/trace"

	"google.golang.org/protobuf/encoding/protojson"
)

// Config holds the desktop client configuration.
type Config struct {
	GatewayURL string `json:"gateway_url"`
	Env        string `json:"env,omitempty"`
}

// Client is an HTTP client for the game gateway REST API.
type Client struct {
	cfg  Config
	http *http.Client
}

// NewClient creates a new Client with the given config.
func NewClient(cfg Config) *Client {
	return &Client{
		cfg:  cfg,
		http: &http.Client{Transport: trace.NewHTTPTransport()},
	}
}

// url constructs a full URL from the config's GatewayURL and the given path.
// It strips any trailing slash from GatewayURL before appending the path.
func (c *Client) url(path string) string {
	return strings.TrimSuffix(c.cfg.GatewayURL, "/") + path
}

// setCommonHeaders sets headers common to all requests.
func (c *Client) setCommonHeaders(req *http.Request) {
	req.Header.Set("Content-Type", "application/json")
	if c.cfg.Env != "" {
		req.Header.Set("env", c.cfg.Env)
	}
}

// CreateSession creates a new game session via POST to /api/v1/sessions.
// The session ID is generated by the server — no session_id is sent in the request.
func (c *Client) CreateSession(ctx context.Context) (*game.Session, error) {
	body, err := protojson.Marshal(new(game.CreateSessionRequest))
	if err != nil {
		return nil, fmt.Errorf("create session: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.url("/api/v1/sessions"), bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("create session: %w", err)
	}
	c.setCommonHeaders(req)

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("create session: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("create session: status %d: %s", resp.StatusCode, string(respBody))
	}

	session := new(game.Session)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, session); err != nil {
		return nil, fmt.Errorf("create session: %w", err)
	}
	return session, nil
}

// ListSessions lists all sessions via GET to /api/v1/sessions.
// Query parameters page_size and page_token control pagination.
func (c *Client) ListSessions(ctx context.Context, pageSize int32, pageToken string) (*game.ListSessionsResponse, error) {
	path := c.url("/api/v1/sessions")
	params := []string{}
	if pageSize > 0 {
		params = append(params, fmt.Sprintf("page_size=%d", pageSize))
	}
	if pageToken != "" {
		params = append(params, fmt.Sprintf("page_token=%s", pageToken))
	}
	if len(params) > 0 {
		path += "?" + strings.Join(params, "&")
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, path, nil)
	if err != nil {
		return nil, fmt.Errorf("list sessions: %w", err)
	}
	c.setCommonHeaders(req)

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("list sessions: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("list sessions: status %d: %s", resp.StatusCode, string(respBody))
	}

	result := new(game.ListSessionsResponse)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, result); err != nil {
		return nil, fmt.Errorf("list sessions: %w", err)
	}
	return result, nil
}

// GetSession retrieves a session by ID via GET to /api/v1/sessions/{sessionID}.
func (c *Client) GetSession(ctx context.Context, sessionID string) (*game.Session, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, c.url("/api/v1/sessions/"+sessionID), nil)
	if err != nil {
		return nil, fmt.Errorf("get session: %w", err)
	}
	c.setCommonHeaders(req)

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("get session: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("get session: status %d: %s", resp.StatusCode, string(respBody))
	}

	session := new(game.Session)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, session); err != nil {
		return nil, fmt.Errorf("get session: %w", err)
	}
	return session, nil
}

// DeleteSession deletes a session by ID via DELETE to /api/v1/sessions/{sessionID}.
func (c *Client) DeleteSession(ctx context.Context, sessionID string) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, c.url("/api/v1/sessions/"+sessionID), nil)
	if err != nil {
		return fmt.Errorf("delete session: %w", err)
	}
	c.setCommonHeaders(req)

	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("delete session: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("delete session: status %d: %s", resp.StatusCode, string(respBody))
	}
	return nil
}

// CreateAgent creates a new agent for a session via POST to /api/v1/sessions/{sessionID}/agent.
func (c *Client) CreateAgent(ctx context.Context, sessionID string) (*game.Agent, error) {
	body, err := protojson.Marshal(&game.CreateAgentRequest{
		Agent: new(game.Agent),
	})
	if err != nil {
		return nil, fmt.Errorf("create agent: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.url("/api/v1/sessions/"+sessionID+"/agent"), bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("create agent: %w", err)
	}
	c.setCommonHeaders(req)

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("create agent: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("create agent: status %d: %s", resp.StatusCode, string(respBody))
	}

	agent := new(game.Agent)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, agent); err != nil {
		return nil, fmt.Errorf("create agent: %w", err)
	}
	return agent, nil
}

// CreateAgentWithProfile creates a new agent for a session with an agent profile via POST to /api/v1/sessions/{sessionID}/agent.
func (c *Client) CreateAgentWithProfile(ctx context.Context, sessionID string, profileName string) (*game.Agent, error) {
	body, err := protojson.Marshal(&game.CreateAgentRequest{
		Agent:            new(game.Agent),
		AgentProfileName: profileName,
	})
	if err != nil {
		return nil, fmt.Errorf("create agent with profile: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.url("/api/v1/sessions/"+sessionID+"/agent"), bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("create agent with profile: %w", err)
	}
	c.setCommonHeaders(req)

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("create agent with profile: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("create agent with profile: status %d: %s", resp.StatusCode, string(respBody))
	}

	agent := new(game.Agent)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, agent); err != nil {
		return nil, fmt.Errorf("create agent with profile: %w", err)
	}
	return agent, nil
}

// ListAgentProfiles lists agent profiles via GET to /api/v1/prompts/agentProfiles.
func (c *Client) ListAgentProfiles(ctx context.Context, pageSize int32, pageToken string) (*game.ListAgentProfilesResponse, error) {
	path := c.url("/api/v1/prompts/agentProfiles")
	params := []string{}
	if pageSize > 0 {
		params = append(params, fmt.Sprintf("page_size=%d", pageSize))
	}
	if pageToken != "" {
		params = append(params, fmt.Sprintf("page_token=%s", pageToken))
	}
	if len(params) > 0 {
		path += "?" + strings.Join(params, "&")
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, path, nil)
	if err != nil {
		return nil, fmt.Errorf("list agent profiles: %w", err)
	}
	c.setCommonHeaders(req)

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("list agent profiles: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("list agent profiles: status %d: %s", resp.StatusCode, string(respBody))
	}

	result := new(game.ListAgentProfilesResponse)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, result); err != nil {
		return nil, fmt.Errorf("list agent profiles: %w", err)
	}
	return result, nil
}

// GetAgent retrieves the agent for a session via GET to /api/v1/sessions/{sessionID}/agent.
func (c *Client) GetAgent(ctx context.Context, sessionID string) (*game.Agent, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, c.url("/api/v1/sessions/"+sessionID+"/agent"), nil)
	if err != nil {
		return nil, fmt.Errorf("get agent: %w", err)
	}
	c.setCommonHeaders(req)

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("get agent: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("get agent: status %d: %s", resp.StatusCode, string(respBody))
	}

	agent := new(game.Agent)
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, agent); err != nil {
		return nil, fmt.Errorf("get agent: %w", err)
	}
	return agent, nil
}

// DeleteAgent deletes the agent for a session via DELETE to /api/v1/sessions/{sessionID}/agent.
func (c *Client) DeleteAgent(ctx context.Context, sessionID string) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, c.url("/api/v1/sessions/"+sessionID+"/agent"), nil)
	if err != nil {
		return fmt.Errorf("delete agent: %w", err)
	}
	c.setCommonHeaders(req)

	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("delete agent: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("delete agent: status %d: %s", resp.StatusCode, string(respBody))
	}
	return nil
}

