version: "3.0"
name: agent
app: game
kind: stateful
desc: game agent service
ports:
  - name: grpc
    port: 50051
artifacts:
  - name: agent
    target: :cmd_image
    tls: true
    secrets:
      - provider
  - name: agent_test
    target: :cmd_image_test
    tls: true
    secrets:
      - provider
