load("@rules_go//go:def.bzl", "go_library")
load("//tools/dev/go:defs.bzl", "go_unittest")

go_library(
    name = "handler",
    srcs = ["handler.go"],
    importpath = "dominion/projects/game/proxy/handler",
    visibility = ["//visibility:public"],
    deps = [
        "//projects/game",
        "//projects/game/proxy/domain",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)

go_unittest(
    name = "handler_test",
    srcs = ["handler_test.go"],
    embed = [":handler"],
    deps = [
        "//projects/game",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//metadata",
        "@org_golang_google_grpc//status",
    ],
)
