load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "handler",
    srcs = ["handler.go"],
    importpath = "dominion/projects/game/proxy/handler",
    visibility = ["//visibility:public"],
    deps = [
        "//common/gopkg/logs",
        "//common/gopkg/logs/event",
        "//common/gopkg/solver",
        "//projects/game",
        "//projects/game/proxy/domain",
        "//projects/game/proxy/runtime",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//types/known/emptypb",
        "@org_golang_google_protobuf//types/known/timestamppb",
        "@org_golang_x_sync//errgroup",
    ],
)
