load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "app",
    srcs = ["worker.go"],
    importpath = "dominion/projects/infra/deploy/app",
    visibility = ["//visibility:public"],
    deps = [
        "//common/gopkg/bootstrap",
        "//common/gopkg/logs",
        "//projects/infra/deploy/domain",
        "//projects/infra/deploy/service",
    ],
)
