load("@rules_go//go:def.bzl", "go_library")
load("//tools/dev/go:defs.bzl", "go_unittest")

go_library(
    name = "sessionmanager",
    srcs = ["manager.go"],
    importpath = "dominion/projects/game/runtime/domain/sessionmanager",
    visibility = ["//visibility:public"],
    deps = [
        "//common/gopkg/bootstrap",
        "//projects/game/runtime/domain",
    ],
)

go_unittest(
    name = "sessionmanager_test",
    srcs = ["session_test.go"],
    embed = [":sessionmanager"],
    deps = ["//projects/game/runtime/domain"],
)
