load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "testutil",
    srcs = ["testutil.go"],
    importpath = "dominion/projects/game/pkg/testutil",
    visibility = ["//visibility:public"],
    deps = [
        "//projects/game/pkg/token",
        "//projects/game/session",
        "@com_github_coder_websocket//:websocket",
        "@org_golang_google_protobuf//encoding/protojson",
        "@org_golang_google_protobuf//proto",
    ],
)
