load("//tools/dev/go:defs.bzl", "go_unittest")
load("//tools/release/wails:defs.bzl", "wails_asset_library")

wails_asset_library(
    name = "windows_agent_assets",
    package_name = "assets",
    src = "//projects/game/windows_agent/frontend:dist",
    out = "frontend_dist",
    importpath = "dominion/projects/game/windows_agent/assets",
    variable_name = "FrontendDist",
    visibility = ["//visibility:public"],
)

go_unittest(
    name = "assets_test",
    srcs = ["assets_test.go"],
    deps = ["//projects/game/windows_agent/assets:windows_agent_assets"],
)
