load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("//tools/dev/go:defs.bzl", "go_unittest")

go_library(
    name = "inspect_wails_config_lib",
    srcs = ["inspect.go"],
    importpath = "dominion/tools/wails/helpers/inspect_config",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "inspect_wails_config",
    embed = [":inspect_wails_config_lib"],
    visibility = ["//visibility:public"],
)

go_unittest(
    name = "inspect_config_test",
    srcs = ["inspect_test.go"],
    embed = [":inspect_wails_config_lib"],
)
