load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("//tools/release:defs.bzl", "artifact_image", "artifact_pkg_go")

go_library(
    name = "cmd_lib",
    srcs = ["main.go"],
    importpath = "dominion/experimental/golang/mongo_demo/cmd",
    visibility = ["//visibility:private"],
    deps = [
        "//common/gopkg/grpc",
        "//common/gopkg/mongo",
        "//experimental/golang/mongo_demo",
        "//experimental/golang/mongo_demo/storage",
        "@grpc_ecosystem_grpc_gateway//runtime",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//reflection",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//types/known/emptypb",
    ],
)

go_binary(
    name = "cmd",
    embed = [":cmd_lib"],
    visibility = ["//visibility:public"],
)

artifact_pkg_go(
    name = "service_pkg",
    app = "mongo-demo",
    binary = ":cmd",
    service = "service",
)

artifact_image(
    name = "cmd_image",
    app = "mongo-demo",
    pkg = ":service_pkg",
    service = "service",
)
