name: cmd
app: mongo-demo
desc: mongo demo gRPC service and HTTP gateway
kind: stateless
ports:
  - name: grpc
    port: 50051
  - name: http
    port: 80
artifacts:
  - name: cmd
    target: :cmd_image
    tls: true
