namespace: "default"
managed_by: "dominion.io"
gateway:
  name: "traefik-gateway"
  namespace: "ingress"
tls:
  secret: "my-https-cert"
  domain: "tls.liukexin.com"
  ca_config_map:
    name: "my-ca.crt"
    key: "ca.crt"
