load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "app",
    srcs = ["router.go"],
    importpath = "dominion/projects/game/gateway/app",
    visibility = ["//visibility:public"],
    deps = [
        "//projects/game/gateway/runtime/owner",
        "//projects/game/pkg/token",
    ],
)
