load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("//tools/dev/go:defs.bzl", "go_unittest")

go_library(
    name = "helpers_lib",
    srcs = ["generate_winres.go"],
    importpath = "dominion/tools/wails/helpers",
    visibility = ["//visibility:private"],
    deps = [
        "@com_github_tc_hib_winres//:winres",
        "@com_github_tc_hib_winres//version",
    ],
)

go_binary(
    name = "generate_winres",
    embed = [":helpers_lib"],
    visibility = ["//visibility:public"],
)

go_unittest(
    name = "helpers_test",
    srcs = ["generate_winres_test.go"],
    embed = [":helpers_lib"],
)
